langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-bbab77db71004bc9a6e6c9c7a8c9883a
      model-name: deepseek-flash
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-bbab77db71004bc9a6e6c9c7a8c9883a
      model-name: deepseek-flash
      log-requests: true
      log-responses: true

logging:
  level:
    dev.langchain4j: DEBUG

spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/volunteer?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "@Zhangzhe0090155"

mybatis:
  configuration:
    map-underscore-to-camel-case: true